---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-deployment
  labels:
    app: {{ include "fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "fullname" . }}
    spec:
      volumes:
        - name: {{ include "fullname" . }}-cm
          configMap:
            name: {{ include "fullname" . }}-cm
      containers:
        - name: prom-external-exporter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 9100
          volumeMounts:
            - name: {{ include "fullname" . }}-cm
              mountPath: /src/config.yml
              subPath: config.yml
