---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" . }}-svc
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
  selector:
    app: {{ include "fullname" . }}
